name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: nullplatform/actions-nullplatform/.github/workflows/release.yml@main
    secrets: inherit
